<a href="https://colab.research.google.com/github/Tee-Sarun/DADS5001/blob/main/Plotly_go.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.express as px

df = px.data.gapminder()
df.head()
df = px.data.gapminder().query("country=='Thailand'")
fig = px.line(df, x="year", y="lifeExp", title='Life expectancy in Thailand')
fig.show()

In [ ]:
import plotly.express as px

df = px.data.gapminder().query("continent=='Asia'")
print(df.head())
fig = px.line(df, x="year", y="lifeExp", color='country', symbol='country')
fig.show()

       country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  


In [1]:
import plotly.express as px

df = px.data.gapminder().query("continent=='Asia'")
print(df.head())
fig = px.line(df, x="year", y="gdpPercap", color='country', symbol='country')
fig.show()

       country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  


In [ ]:
import plotly.express as px

df = px.data.stocks()
print(df.head())
print(df.shape)
fig = px.line(df, x='date', y="GOOG")
fig.show()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
(105, 7)


In [5]:
import plotly.express as px
df = px.data.stocks(indexed=True)
fig = px.line(df, facet_row="company", facet_row_spacing=0.01, height=300, width=400)

fig.show(config=dict(displayModeBar=False))

In [2]:
import plotly.express as px
df = px.data.stocks(indexed=True)
fig = px.line(df, facet_row="company", facet_row_spacing=0.01, height=400, width=400)

# hide and lock down axes
fig.update_xaxes(visible=False, fixedrange=True)
fig.update_yaxes(visible=False, fixedrange=True)

# remove facet/subplot labels
fig.update_layout(annotations=[], overwrite=True)

# strip down the rest of the plot
fig.update_layout(
    showlegend=False,
    plot_bgcolor="blue",
    margin=dict(t=10,l=10,b=10,r=10)
)

# disable the modebar for such a small plot
fig.show(config=dict(displayModeBar=False))

In [15]:
import plotly.express as px
df = px.data.stocks(indexed=True)
fig = px.bar(df, facet_row="company", facet_row_spacing=0.01, height=400, width=600)

# hide and lock down axes
fig.update_xaxes(visible=False, fixedrange=True)
fig.update_yaxes(visible=False, fixedrange=True)

# remove facet/subplot labels
fig.update_layout(annotations=[], overwrite=True)

# strip down the rest of the plot
fig.update_layout(
    showlegend=False,
    #plot_bgcolor="blue",
    margin=dict(t=10,l=10,b=10,r=10)
)

# disable the modebar for such a small plot
fig.show(config=dict(displayModeBar=False))

ValueError: Value of 'facet_row' is not the name of a column in 'data_frame'. Expected one of ['date', 'GOOG', 'AAPL', 'AMZN', 'FB', 'NFLX', 'MSFT'] but received: company

In [ ]:
df.columns

Index(['date', 'GOOG', 'AAPL', 'AMZN', 'FB', 'NFLX', 'MSFT'], dtype='object')

In [16]:
import plotly.graph_objects as go
'''
# Create random data with numpy
import numpy as np
np.random.seed(1)

N = 100
random_x = np.linspace(0, 1, N)
random_y0 = np.random.randn(N) + 5
random_y1 = np.random.randn(N)
random_y2 = np.random.randn(N) - 5
'''
# Create traces
fig = go.Figure()
fig.add_trace(go.Scatter(x=df.date, y=df.GOOG,
                    mode='lines',
                    name='Google'))
fig.add_trace(go.Scatter(x=df.date, y=df.AAPL,
                    mode='lines+markers',
                    name='Apple'))
fig.add_trace(go.Scatter(x=df.date, y=df.AMZN,
                    mode='markers', name='Amazon'))

fig.show()

In [31]:
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

# โหลดข้อมูลหุ้น
df = px.data.stocks()

# คำนวณความแตกต่างของราคาระหว่างหุ้น
stocks = ['GOOG', 'AAPL', 'AMZN', 'MSFT'] #,'FB', 'NFLX'
diff_cols = []
for i in range(len(stocks)):
    for j in range(i + 1, len(stocks)):
        col_name = f'{stocks[i]}-{stocks[j]}_diff'
        df[col_name] = df[stocks[i]] - df[stocks[j]]
        diff_cols.append(col_name)

# สร้างกราฟ
fig = go.Figure()

# เพิ่ม traces สำหรับหุ้น
for stock in stocks:
    hovertemplate = f'Date: %{{x}}<br>{stock}: %{{y:.2f}}<br>'
    customdata_cols = []
    for diff_col in diff_cols:
        if stock in diff_col:
            hovertemplate += f'{diff_col}: %{{customdata[{len(customdata_cols)}]:.2f}}<br>'
            customdata_cols.append(diff_col)

    fig.add_trace(go.Scatter(
        x=df['date'], y=df[stock],
        mode='lines+markers' if stock in ['AAPL', 'MSFT'] else ('markers' if stock == 'AMZN' else 'lines'),
        name=stock,
        hovertemplate=hovertemplate + '<extra></extra>',
        customdata=df[customdata_cols] if customdata_cols else None
    ))


# เพิ่มเส้นแนวตั้งสีแดงที่วันที่ตัวอย่าง (เช่น วันที่แรกในข้อมูล)
example_date = df['date'].iloc[0]
fig.add_vline(x=example_date, line=dict(color='red', width=2, dash='dash'))

# ปรับแต่ง layout
fig.update_layout(
    title='Stock Prices with Price Differences and Vertical Line',
    xaxis_title='Date',
    yaxis_title='Price',
    hovermode='x unified'  # ทำให้ tooltip รวมข้อมูลทุก trace ที่ x เดียวกัน
)

# แสดงกราฟ
fig.show()

In [32]:
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

# โหลดข้อมูลหุ้น
df = px.data.stocks()

# คำนวณความแตกต่างของราคาโดยใช้หุ้นแต่ละตัวเป็นฐาน
df['GOOG_AAPL_diff'] = df['GOOG'] - df['AAPL']
df['GOOG_AMZN_diff'] = df['GOOG'] - df['AMZN']
df['GOOG_MSFT_diff'] = df['GOOG'] - df['MSFT']
df['AAPL_GOOG_diff'] = df['AAPL'] - df['GOOG']
df['AAPL_AMZN_diff'] = df['AAPL'] - df['AMZN']
df['AAPL_MSFT_diff'] = df['AAPL'] - df['MSFT']
df['AMZN_GOOG_diff'] = df['AMZN'] - df['GOOG']
df['AMZN_AAPL_diff'] = df['AMZN'] - df['AAPL']
df['AMZN_MSFT_diff'] = df['AMZN'] - df['MSFT']
df['MSFT_GOOG_diff'] = df['MSFT'] - df['GOOG']
df['MSFT_AAPL_diff'] = df['MSFT'] - df['AAPL']
df['MSFT_AMZN_diff'] = df['MSFT'] - df['AMZN']

# สร้างกราฟ
fig = go.Figure()

# เพิ่ม trace สำหรับ Google
fig.add_trace(go.Scatter(
    x=df['date'], y=df['GOOG'],
    mode='lines',
    name='Google',
    hovertemplate='Date: %{x}<br>Google: %{y:.2f}<br>' +
                  'GOOG-AAPL Diff: %{customdata[0]:.2f}<br>' +
                  'GOOG-AMZN Diff: %{customdata[1]:.2f}<br>' +
                  'GOOG-MSFT Diff: %{customdata[2]:.2f}<extra></extra>',
    customdata=df[['GOOG_AAPL_diff', 'GOOG_AMZN_diff', 'GOOG_MSFT_diff']]
))

# เพิ่ม trace สำหรับ Apple
fig.add_trace(go.Scatter(
    x=df['date'], y=df['AAPL'],
    mode='lines+markers',
    name='Apple',
    hovertemplate='Date: %{x}<br>Apple: %{y:.2f}<br>' +
                  'AAPL-GOOG Diff: %{customdata[0]:.2f}<br>' +
                  'AAPL-AMZN Diff: %{customdata[1]:.2f}<br>' +
                  'AAPL-MSFT Diff: %{customdata[2]:.2f}<extra></extra>',
    customdata=df[['AAPL_GOOG_diff', 'AAPL_AMZN_diff', 'AAPL_MSFT_diff']]
))

# เพิ่ม trace สำหรับ Amazon
fig.add_trace(go.Scatter(
    x=df['date'], y=df['AMZN'],
    mode='markers',
    name='Amazon',
    hovertemplate='Date: %{x}<br>Amazon: %{y:.2f}<br>' +
                  'AMZN-GOOG Diff: %{customdata[0]:.2f}<br>' +
                  'AMZN-AAPL Diff: %{customdata[1]:.2f}<br>' +
                  'AMZN-MSFT Diff: %{customdata[2]:.2f}<extra></extra>',
    customdata=df[['AMZN_GOOG_diff', 'AMZN_AAPL_diff', 'AMZN_MSFT_diff']]
))

# เพิ่ม trace สำหรับ Microsoft
fig.add_trace(go.Scatter(
    x=df['date'], y=df['MSFT'],
    mode='markers',
    name='Microsoft',
    hovertemplate='Date: %{x}<br>Microsoft: %{y:.2f}<br>' +
                  'MSFT-GOOG Diff: %{customdata[0]:.2f}<br>' +
                  'MSFT-AAPL Diff: %{customdata[1]:.2f}<br>' +
                  'MSFT-AMZN Diff: %{customdata[2]:.2f}<extra></extra>',
    customdata=df[['MSFT_GOOG_diff', 'MSFT_AAPL_diff', 'MSFT_AMZN_diff']]
))



# ปรับแต่ง layout
fig.update_layout(
    title='Stock Prices with Dynamic Price Differences and Vertical Line',
    xaxis_title='Date',
    yaxis_title='Price',
    hovermode='x unified'  # รวมข้อมูลทุก trace ที่ x เดียวกัน
)

# แสดงกราฟ
fig.show()

In [8]:
import plotly.graph_objects as go
import numpy as np

title = 'Main Source for News'
labels = ['Television', 'Newspaper', 'Internet', 'Radio']
colors = ['rgb(67,67,67)', 'rgb(115,115,115)', 'rgb(49,130,189)', 'rgb(189,189,189)']

mode_size = [8, 8, 12, 8]
line_size = [2, 2, 4, 2]

x_data = np.vstack((np.arange(2001, 2014),)*4)
print(x_data)

y_data = np.array([
    [74, 82, 80, 74, 73, 72, 74, 70, 70, 66, 66, 69],
    [45, 42, 50, 46, 36, 36, 34, 35, 32, 31, 31, 28],
    [13, 14, 20, 24, 20, 24, 24, 40, 35, 41, 43, 50],
    [18, 21, 18, 21, 16, 14, 13, 18, 17, 16, 19, 23],
])

fig = go.Figure()

for i in range(0, 4):
    fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], mode='lines',
        name=labels[i],
        line=dict(color=colors[i], width=line_size[i]),
        connectgaps=True,
    ))

    # endpoints
    fig.add_trace(go.Scatter(
        x=[x_data[i][0], x_data[i][-1]],
        y=[y_data[i][0], y_data[i][-1]],
        mode='markers',
        marker=dict(color=colors[i], size=mode_size[i])
    ))
    print([x_data[i][0], x_data[i][-1]])

fig.update_layout(
    xaxis=dict(
        showline=True,
        showgrid=False,
        showticklabels=True,
        linecolor='rgb(204, 204, 204)',
        linewidth=2,
        ticks='outside',
        tickfont=dict(
            family='Arial',
            size=12,
            color='rgb(82, 82, 82)',
        ),
    ),
    yaxis=dict(
        showgrid=False,
        zeroline=False,
        showline=False,
        showticklabels=False,
    ),
    autosize=False,
    margin=dict(
        autoexpand=False,
        l=100,
        r=20,
        t=110,
    ),
    showlegend=False,
    plot_bgcolor='white'
)

annotations = []

# Adding labels
for y_trace, label, color in zip(y_data, labels, colors):
    # labeling the left_side of the plot
    annotations.append(dict(xref='paper', x=0.05, y=y_trace[0],
                                  xanchor='right', yanchor='middle',
                                  text=label + ' {}%'.format(y_trace[0]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
    # labeling the right_side of the plot
    annotations.append(dict(xref='paper', x=0.95, y=y_trace[11],
                                  xanchor='left', yanchor='middle',
                                  text='{}%'.format(y_trace[11]),
                                  font=dict(family='Arial',
                                            size=16),
                                  showarrow=False))
# Title
annotations.append(dict(xref='paper', yref='paper', x=0.0, y=1.05,
                              xanchor='left', yanchor='bottom',
                              text='Main Source for News',
                              font=dict(family='Arial',
                                        size=30,
                                        color='rgb(37,37,37)'),
                              showarrow=False))
# Source
annotations.append(dict(xref='paper', yref='paper', x=0.5, y=-0.1,
                              xanchor='center', yanchor='top',
                              text='Source: PewResearch Center & ' +
                                   'Storytelling with data',
                              font=dict(family='Arial',
                                        size=12,
                                        color='rgb(150,150,150)'),
                              showarrow=False))

fig.update_layout(annotations=annotations)

fig.show()

[[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]
 [2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013]]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
[np.int64(2001), np.int64(2013)]
